---
trust-domain: "ap"
task-priority: low

taskgraph:
  cached-task-prefix: "ap.v2.botguette"
  repositories:
    botguette:
      name: "botguette"

  register: eije_taskgraph:register

workers:
  aliases: {}
